name: assignment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-131.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  crypto: ^3.0.3
  csv: ^5.1.1
  excel: ^4.0.2
  http: ^1.2.0
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  fl_chart: ^0.66.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/